services:
    database_ignite:
        image: postgres
        container_name: database-ignite
        restart: always
        ports:
            - 5432:5432
        environment:
            - POSTGRES_USER=docker
            - POSTGRES_PASSWORD=developer@guilherme
            - POSTGRES_DB=ignite
        volumes:
            - pgdata:/data/postgres

    app:
        build: .
        container_name: api-dev
        ports:
            - 3333:3333
            - 9929:9929
        volumes:
            - .:/usr/app
        links:
            - database_ignite
        depends_on:
            - database_ignite

volumes:
 pgdata:
    driver: local
